# ขนาดและรูปร่างหุ่นยนต์
footprint: [[-0.15, -0.125], [-0.15, 0.125], [0.15, 0.125], [0.15, -0.125]] #ขนาดและรูปร่างของหุ่นยนต์ (พิกัด XY)	[[x1,y1], [x2,y2]]
#robot_radius: 0.2        # รัศมีของหุ่นยนต์ (ใช้แทน footprint หากทรงกลม)
transform_tolerance: 0.5  # เวลารอคอยสำหรับข้อมูล tf 0.5 (วินาที)
resolution: 0.05          #ความละเอียดของ grid ใน costmap 0.05 (เมตร/เซลล์)

# Obstacle Layer (ชั้นสิ่งกีดขวาง)
obstacle_layer:
  enabled: true
  obstacle_range: 2.5       #ระยะที่เซนเซอร์สามารถตรวจจับสิ่งกีดขวางได้	2.5 (เมตร)
  raytrace_range: 3.0       #ระยะที่เซนเซอร์สามารถลบสิ่งกีดขวางออกได้	3.0 (เมตร)
  max_obstacle_height: 0.6  #ความสูงสูงสุดของสิ่งกีดขวางที่จะตรวจจับ	0.6 (เมตร)
  observation_sources: laser_scan  #รายชื่อเซนเซอร์ที่ใช้ตรวจจับสิ่งกีดขวาง	laser_scan sensor
  laser_scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}

# Inflation Layer  (ชั้นกันชนรอบสิ่งกีดขวาง)
inflation_layer:
  enabled: true
  inflation_radius: 0.3  #ระยะกันชนรอบสิ่งกีดขวาง	0.3 (เมตร)
  cost_scaling_factor: 10.0 #ความชันของค่า cost รอบสิ่งกีดขวาง	10.0

# Static Layer (แผนที่คงที่)
static_layer:
  enabled: true #ปิด/ปิดการใช้งาน static map	true / false
  map_topic: "/map" #ชื่อ topic ที่ใช้ดึงข้อมูลแผนที่	/map


#z_resolution	        #ความละเอียดในแนวดิ่ง	0.05 (เมตร)
#z_voxels	จำนวน voxel #ในแนวดิ่ง	10
#unknown_threshold	  #จำนวน voxel ที่ต้องถูกระบุว่าไม่รู้จัก	10
#mark_threshold	      #จำนวน voxel ที่ต้องระบุว่าเป็นสิ่งกีดขวาง	5