global_costmap:
  global_frame: map             # กรอบอ้างอิงหลัก (map frame)
  robot_base_frame: base_link   # กรอบฐานของหุ่นยนต์
  update_frequency: 5.0         # ความถี่ในการอัปเดต costmap (Hz)
  publish_frequency: 2.0        # ความถี่ในการเผยแพร่ costmap (Hz)
  transform_tolerance: 0.5      # เวลารอคอย tf (วินาที)
  resolution: 0.05              # ความละเอียดของกริด (เมตร/เซลล์)

  static_map: true              # ใช้ static map จาก map_server
  rolling_window: false         # false = แผนที่ไม่เคลื่อนที่ตามหุ่นยนต์

  width: 10.0                   # ความกว้างของ costmap (เมตร) หาก rolling_window = true
  height: 10.0                  # ความสูงของ costmap (เมตร) หาก rolling_window = true

  plugins:                      # 🧩 เลเยอร์ที่ใช้งานใน global costmap
    - {name: static_layer,        type: \"costmap_2d::StaticLayer\"}
    - {name: obstacle_layer,      type: \"costmap_2d::ObstacleLayer\"}
    - {name: inflation_layer,     type: \"costmap_2d::InflationLayer\"}

  static_layer:
    enabled: true
    map_topic: /map

  obstacle_layer:
    enabled: true
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

  inflation_layer:
    enabled: true
    inflation_radius: 0.3
    cost_scaling_factor: 5.0


